language: c++
sudo: required
dist: trusty

notifications:
  email:
    on_success: never
    on_failure: change

env:
  global:
    - secure: UUtdYLhd9+cY+bMrcRvvtjmsQBqM5L9zgzyLeQZLMmmWbHwLsfpQask9A8eD1oc1K1o0tYmK+Qk1flxNTbnUtlryPNgJxJ95a/TwLl1P9yN6plMleNbuwMs5dyS9VnmcK3LzDFuoje/9rtX2seNR2PW2EJSvPz20ENaT693Kfa8=
    - secure: G8rRE17KDx83crRLQSEkIyvMbXlbpKDvIYoKE+y9Bg3qu79tsB/RrNdo6OGHx4x3KhBGpuo4NdN/4FAGS599P4W+KN3kNr9VFSCMJhJK59+KkYfGq2rX1oGDhB4B1xjVk0tj6bFIJ333hVLEYFviIKYxRSZfnKa0RmgBJZbvMfs=

matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
      language: cpp
      compiler: clang
      env: TARGET=linux_clang CONAN_COMPILER='clang' CONAN_COMPILER_VERSION='3.9'

    - os: linux
      sudo: required
      dist: trusty
      language: cpp
      compiler: gcc
      env: TARGET=linux_gcc CONAN_COMPILER='gcc' CONAN_COMPILER_VERSION='6.3'

    - os: linux
      sudo: required
      dist: trusty
      env: TARGET=apidoc
      # We check for gcc when deciding to deploy: so this is only an indicator that we want to deploy this branch.
      language: cpp
      compiler: gcc
      git:
        submodules: false

    - os: linux
      sudo: required
      dist: trusty
      env: TARGET=new_version_tagger
      git:
        submodules: false
      branches:
        only:
          - master

before_install:
  - bash tool/travis.sh target_before_install

script:
  - bash tool/travis.sh target_script

after_success:
  - bash tool/travis.sh target_after_success

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    - secure: DgFzibKfjjD4v6zP51sjyP+chyBNKA6D3LHz4+pKN2mSBLSFeqK29z+38TlIOJHSpq6pWdvxqHjn+vQuYV1v/oqri0AVpo0kxFojtNaIFo1Dc/Sfv76V7X6p9+JaSRtKtqCjOV7QP9fftyUgSu1Bq67fwuv6QvDgOzdQIcV87bA=
  file_glob: true
  file: /tmp/inexor-build/inexor-core-*.zip
  overwrite: true
  on:
    # Deploy only if build was caused by a tag push.
    tags: true
    condition: "$CC = gcc"
    repo: inexorgame/inexor-core
